log syslog all;
router id 139.84.164.110;

protocol device {}

protocol static {
  ipv6;
  route 2a0a:6040:4002::/48 blackhole;
  route 2a0a:6040:4003::/48 blackhole;
  route 2a0a:6040:4004::/48 blackhole;
  route 2a0a:6040:4006::/48 blackhole;
  route 2a0a:6040:4064::/48 blackhole;
  route 2a0a:6040:4050::/44 blackhole;
}

protocol kernel {
  metric 4096;
  ipv6 { export where source = RTS_STATIC; };
}

protocol bgp vultr {
  local as 199347;
  neighbor 2001:19f0:ffff::1 as 64515;
  source address 2401:c080:3400:2e43:5400:4ff:fe5a:5550;
  multihop 2;
  graceful restart on;
  authentication md5;
  password bgp_password;
  ipv6 {
    import none;
    export where source = RTS_STATIC;
  };
}
