{ lib, namespace, ... }:
with lib;
with lib.${namespace};
let
  inherit (lib)
    mkEnableOption
    mkMerge
    mkForce
    types
    ;

  genBridgedContainer =
    {
      name,
      vlan,
      config,
      specialArgs ? { },
    }:
    {
      # Generate the container entry
      containers.${name} = {
        autoStart = true;
        privateNetwork = true;
        # Plug into host bridge
        hostBridge = "br0";

        inherit config;
        inherit specialArgs;
      };

      # Container Trunk Port (Host-side of the vbridge)
      systemd.network.networks."30-container-${name}" = {
        matchConfig.Name = "vb-${name}";
        networkConfig = {
          Bridge = "br0";
        };
        linkConfig.RequiredForOnline = "no";
        bridgeVLANs = [
          {
            VLAN = vlan;
            PVID = vlan;
            EgressUntagged = vlan;
          }
        ];
      };
    };

  genServiceOptions =
    {
      name,
      monitor ? { },
    }:
    let
      protocol = monitor.protocol or "tcp";
    in
    {
      enable = mkEnableOption name;

      volumeConfig =
        mkOpt (types.attrsOf types.attrs) { }
          "Volume configurations generated by mkContainerVolume";

      monitor = {
        enable = mkBoolOpt (monitor.enable or true) "Whether to generate a Gatus check for this service.";
        name = mkOpt types.str (monitor.name or name) "Gatus endpoint name.";
        group = mkOpt types.str (monitor.group or "services") "Gatus endpoint group.";
        protocol = mkOpt (types.enum [
          "http"
          "https"
          "tcp"
          "udp"
          "icmp"
          "icmpv6"
        ]) protocol "Gatus check protocol.";
        address = mkOpt types.str (monitor.address or "") "Gatus check address.";
        port = mkOpt types.port monitor.port "Gatus check port.";
        path = mkOpt types.str (monitor.path or "/") "Gatus HTTP path.";
        interval = mkOpt types.str (monitor.interval or "30s") "Gatus check interval.";
        conditions = mkOpt (types.listOf types.str) (monitor.conditions or (
          if protocol == "http" || protocol == "https" then
            [ "[STATUS] == 200" ]
          else
            [ "[CONNECTED] == true" ]
        )
        ) "Gatus check conditions.";
      };
    };

  genNspawnService =
    {
      name,
      package,
      vlan,
      port ? [ ],
      description ? name,
      exec ? "/bin/${name}",
      environment ? { },
      serviceConfig ? { },
      containerConfig ? { },
      specialArgs ? { },
    }:
    genBridgedContainer {
      inherit name vlan;
      specialArgs = specialArgs // {
        servicePackage = package;
      };
      config =
        { servicePackage, ... }:
        mkMerge [
          {
            networking = {
              networkmanager = disabled;
              useHostResolvConf = false;
              firewall = enabled // {
                allowedTCPPorts = port;
              };
            };

            # Fix for https://github.com/NixOS/nixpkgs/issues/493934
            security.pam.services.login.updateWtmp = mkForce false;

            documentation = disabled;
            environment.defaultPackages = mkForce [ ];
            environment.systemPackages = mkForce [ ];
            nix = disabled;
            programs.command-not-found = disabled;

            systemd.network = enabled // {
              networks."30-eth0" = {
                matchConfig.Name = "eth0";
                networkConfig = {
                  Description = "${name} service container interface";
                  DHCP = "yes";
                  IPv6AcceptRA = "yes";
                  LLDP = "no";
                  EmitLLDP = "no";
                  LLMNR = "no";
                };
              };
            };

            systemd.services.${name} = {
              inherit description;
              wantedBy = [ "multi-user.target" ];
              inherit environment;
              serviceConfig = {
                ExecStart = "${servicePackage}${exec}";
                Restart = "always";
                DynamicUser = true;
              }
              // serviceConfig;
            };

            system.stateVersion = "26.05";
          }
          containerConfig
        ];
    };
in
{
  mkBridgedContainer = genBridgedContainer;
  mkServiceOptions = genServiceOptions;
  mkNspawnService = genNspawnService;
}
