{ lib, namespace, ... }:
with lib;
with lib.${namespace};
let
  inherit (lib)
    mkEnableOption
    mapAttrsToList
    mkMerge
    mkForce
    types
    ;
  containerProfiles = import ../containers/default.nix { };
  inherit (containerProfiles)
    getNspawnHardeningProfile
    getNspawnIsolationProfile
    ;
  mkContainerMacAddress =
    name:
    let
      hash = builtins.hashString "sha256" name;
      octet = offset: builtins.substring offset 2 hash;
    in
    "02:${octet 0}:${octet 2}:${octet 4}:${octet 6}:${octet 8}";

  # Container mechanics only: nspawn, bridge/VLAN, stable MAC, and host limits.
  genContainerBase =
    {
      name,
      vlan,
      config,
      isolationProfile ? "unprivileged",
      macAddress ? mkContainerMacAddress name,
      resources ? { },
      specialArgs ? { },
    }:
    let
      isolationConfig = getNspawnIsolationProfile isolationProfile;
    in
    {
      # Generate the container entry
      containers.${name} = isolationConfig // {
        autoStart = true;
        privateNetwork = true;
        localMacAddress = macAddress;
        # Plug into host bridge
        hostBridge = "br0";

        inherit config;
        inherit specialArgs;
      };

      # Container Trunk Port (Host-side of the vbridge)
      systemd.network.networks."30-container-${name}" = {
        matchConfig.Name = "vb-${name}";
        networkConfig = {
          Bridge = "br0";
        };
        linkConfig.RequiredForOnline = "no";
        bridgeVLANs = [
          {
            VLAN = vlan;
            PVID = vlan;
            EgressUntagged = vlan;
          }
        ];
      };

      systemd.services."container@${name}".serviceConfig = resources;
    };

  genContainerDefaults =
    {
      name,
      ports ? [ ],
    }:
    {
      networking = {
        networkmanager = disabled;
        useHostResolvConf = false;
        firewall = enabled // {
          allowedTCPPorts = ports;
        };
      };

      # Fix for https://github.com/NixOS/nixpkgs/issues/493934
      security.pam.services.login.updateWtmp = mkForce false;

      documentation = disabled;
      environment.defaultPackages = mkForce [ ];
      environment.systemPackages = mkForce [ ];
      nix = disabled;
      programs.command-not-found = disabled;

      systemd.network = enabled // {
        networks."30-eth0" = {
          matchConfig.Name = "eth0";
          networkConfig = {
            Description = "${name} service container interface";
            DHCP = "yes";
            IPv6AcceptRA = "yes";
            LLDP = "no";
            EmitLLDP = "no";
            LLMNR = "no";
          };
        };
      };

      system.stateVersion = "26.05";
    };

  # Default homelab service container: minimal NixOS guest plus arbitrary inner config.
  genServiceContainer =
    {
      name,
      vlan,
      ports ? port,
      port ? [ ],
      secrets ? { },
      containerConfig ? { },
      isolationProfile ? "unprivileged",
      macAddress ? mkContainerMacAddress name,
      resources ? { },
      specialArgs ? { },
    }:
    let
      repoRoot = ../..;
      mkSecretName = secretName: secret: secret.name or "${name}-${secretName}";
      secretConfig = mkMerge (
        mapAttrsToList (
          secretName: secret:
          let
            sopsName = mkSecretName secretName secret;
            inherit (secret) mountPath;
            hostPath = secret.path or "/run/secrets/${sopsName}";
          in
          {
            sops.secrets.${sopsName} = {
              sopsFile = repoRoot + "/${secret.file}";
              format = secret.format or "dotenv";
              # With privateUsers = "pick", container root is not host root.
              # Read-only bind-mounted secrets must be readable by the mapped uid.
              mode = secret.mode or "0444";
              restartUnits = secret.restartUnits or [ "container@${name}.service" ];
            }
            // optionalAttrs (secret ? path) { inherit (secret) path; };

            containers.${name}.bindMounts.${mountPath} = {
              inherit hostPath;
              isReadOnly = true;
            };
          }
        ) secrets
      );
    in
    mkMerge [
      secretConfig
      (genContainerBase {
        inherit
          name
          vlan
          isolationProfile
          macAddress
          resources
          specialArgs
          ;
        config = mkMerge [
          (genContainerDefaults { inherit name ports; })
          containerConfig
        ];
      })
    ];

  genServiceOptions =
    {
      name,
      monitor ? { },
    }:
    let
      protocol = monitor.protocol or "tcp";
    in
    {
      enable = mkEnableOption name;

      volumeConfig =
        mkOpt (types.attrsOf types.attrs) { }
          "Volume configurations generated by mkContainerVolume";

      monitor = {
        enable = mkBoolOpt (monitor.enable or true) "Whether to generate a Gatus check for this service.";
        name = mkOpt types.str (monitor.name or name) "Gatus endpoint name.";
        group = mkOpt types.str (monitor.group or "services") "Gatus endpoint group.";
        protocol = mkOpt (types.enum [
          "http"
          "https"
          "tcp"
          "udp"
          "icmp"
          "icmpv6"
        ]) protocol "Gatus check protocol.";
        address = mkOpt types.str (monitor.address or "") "Gatus check address.";
        port = mkOpt types.port monitor.port "Gatus check port.";
        path = mkOpt types.str (monitor.path or "/") "Gatus HTTP path.";
        interval = mkOpt types.str (monitor.interval or "30s") "Gatus check interval.";
        conditions = mkOpt (types.listOf types.str) (monitor.conditions or (
          if protocol == "http" || protocol == "https" then
            [ "[STATUS] == 200" ]
          else
            [ "[CONNECTED] == true" ]
        )
        ) "Gatus check conditions.";
      };
    };

  # Convenience wrapper for the common one-container/one-systemd-service case.
  genSingleServiceContainer =
    {
      name,
      package ? null,
      command ? null,
      vlan,
      ports ? port,
      port ? [ ],
      secrets ? { },
      description ? name,
      exec ? "/bin/${name}",
      serviceName ? name,
      environment ? { },
      serviceConfig ? { },
      containerConfig ? { },
      isolationProfile ? "unprivileged",
      hardeningProfile ? "default",
      macAddress ? mkContainerMacAddress name,
      resources ? { },
      specialArgs ? { },
    }:
    let
      hardeningConfig = getNspawnHardeningProfile hardeningProfile;
      execStart =
        if command != null then
          command
        else if package != null then
          "${package}${exec}"
        else
          throw "mkSingleServiceContainer '${name}' requires either 'command' or 'package'.";
    in
    genServiceContainer {
      inherit
        name
        vlan
        ports
        secrets
        isolationProfile
        macAddress
        resources
        ;
      specialArgs = specialArgs // {
        inherit package macAddress;
      };
      containerConfig = mkMerge [
        {
          systemd.services.${serviceName} = {
            inherit description;
            wantedBy = [ "multi-user.target" ];
            inherit environment;
            serviceConfig = {
              ExecStart = execStart;
              Restart = "always";
              DynamicUser = true;
            }
            // hardeningConfig
            // serviceConfig;
          };
        }
        containerConfig
      ];
    };
in
{
  mkContainerBase = genContainerBase;
  mkServiceOptions = genServiceOptions;
  mkServiceContainer = genServiceContainer;
  mkSingleServiceContainer = genSingleServiceContainer;
}
