use crate::apply::run_apply;
use clap::{Parser, Subcommand};
use std::path::PathBuf;

#[derive(Parser)]
#[command(name = "volume")]
#[command(about = "Homelab volume management helper")]
struct Cli {
    /// Desired volume state file generated by NixOS.
    #[arg(long, default_value = "/etc/homelab/volumes.json")]
    state_file: PathBuf,

    #[command(subcommand)]
    command: VolumeCommand,
}

#[derive(Subcommand)]
enum VolumeCommand {
    /// Apply local volume state: create, format, verify, and grow.
    Apply {
        /// Apply without interactive prompts. Shrinks are still refused.
        #[arg(long)]
        yes: bool,

        /// Volume IDs to apply. Defaults to all declared volumes.
        volume_ids: Vec<String>,
    },
}

pub fn run() -> Result<(), String> {
    let cli = Cli::parse();

    match cli.command {
        VolumeCommand::Apply { yes, volume_ids } => run_apply(&cli.state_file, yes, &volume_ids),
    }
}
