use crate::{
    apply::run_apply,
    retire::run_retire,
    transfer::{run_copy, run_receive},
};
use clap::{Parser, Subcommand};
use std::path::PathBuf;

#[derive(Parser)]
#[command(name = "volume")]
#[command(about = "Homelab volume management helper")]
struct Cli {
    /// Desired volume state file generated by NixOS.
    #[arg(long, default_value = "/etc/homelab/volumes.json")]
    state_file: PathBuf,

    #[command(subcommand)]
    command: VolumeCommand,
}

#[derive(Subcommand)]
enum VolumeCommand {
    /// Create missing volumes, verify existing volumes, and grow them when declared larger.
    Apply {
        /// Apply without interactive prompts. Shrinks are always refused.
        #[arg(long)]
        yes: bool,

        /// Volume IDs to apply. Defaults to all declared volumes.
        volume_ids: Vec<String>,
    },

    /// Copy every volume owned by a service to another declared host over SSH.
    Copy {
        owner_service: String,

        /// SSH hostname or address of the destination host.
        #[arg(long)]
        to: String,
    },

    /// Receive one raw volume stream. Invoked by `volume copy` over SSH.
    #[command(hide = true)]
    Receive {
        owner_service: String,
        volume_id: String,

        #[arg(long)]
        source_bytes: u64,
    },

    /// Permanently remove an LV covered by a deployed deletion tombstone.
    Retire {
        volume_id: String,
        #[arg(long)]
        yes: bool,
    },
}

pub fn run() -> Result<(), String> {
    let cli = Cli::parse();

    match cli.command {
        VolumeCommand::Apply { yes, volume_ids } => run_apply(&cli.state_file, yes, volume_ids),
        VolumeCommand::Copy { owner_service, to } => run_copy(&cli.state_file, &owner_service, &to),
        VolumeCommand::Receive {
            owner_service,
            volume_id,
            source_bytes,
        } => run_receive(&cli.state_file, &owner_service, &volume_id, source_bytes),
        VolumeCommand::Retire { volume_id, yes } => run_retire(&cli.state_file, &volume_id, yes),
    }
}
