{
  config,
  lib,
  namespace,
  pkgs,
  ...
}:
with lib;
with lib.${namespace};
let
  srv = config.${namespace}.services;
  cfg = srv.pvr-movies-monitor;
in
{
  options.${namespace}.services.pvr-movies-monitor = with types; {
    enable = mkEnableOption "PVR Movies Monitor";
    host = mkOpt str "" "Listen address for this application";
    port = mkOpt port "" "Port to listen on";
    apiKey = mkOpt str "" "API Key for the application";
    volumeConfig = lib.mkOption {
      type = attrsOf attrs;
      default = { };
      description = "Volume configurations generated by mkContainerVolume";
    };
  };

  config = mkIf cfg.enable (mkMerge [
    {
      containers.pvr-movies-monitor = {
        autoStart = true;
        privateNetwork = true;
        # Plug into host bridge
        hostBridge = "br0";

        specialArgs = {
          inherit namespace;
          pvr-movies-monitor-package = pkgs.${namespace}.pvr-movies-monitor;
        };

        config =
          { pvr-movies-monitor-package, ... }:
          {
            networking = {
              networkmanager = disabled;
              firewall = enabled // {
                allowedTCPPorts = [ cfg.port ];
              };
            };

            users.users.root.shell = pkgs.bashInteractive;

            # Fix for https://github.com/nixos/nixpkgs/issues/493934
            security.pam.services.login.updateWtmp = lib.mkForce false;

            environment.systemPackages = with pkgs; [
              bash
              fish
              kitty.terminfo
            ];

            systemd.network = {
              netdevs = mkTaggedVlanIf 10;
              networks = lib.mkMerge [
                {
                  "30-eth0" = {
                    matchConfig.Name = "eth0";
                    vlan = [ "vlan10" ];
                    networkConfig.LinkLocalAddressing = "no";
                  };
                }
                (mkNetworkIf {
                  name = "vlan10";
                  config = {
                    Description = "Tagged VLAN99 interface for accessing the host";
                    DHCP = "no";
                    IPv6AcceptRA = "no";
                    # TODO: remove duplicates
                    LLDP = "no";
                    EmitLLDP = "no";
                    LLMNR = "no";
                  };
                })
              ];
            };

            systemd.network.wait-online.enable = false;

            systemd.services.pvr-movies-monitor = {
              description = "PVR Movies Monitoring Service";
              wantedBy = [ "multi-user.target" ];
              environment = {
                API_KEY = cfg.apiKey;
                HOST = cfg.host;
                PORT = toString cfg.port;
                RUST_LOG = "info";
              };
              serviceConfig = {
                ExecStart = "${pvr-movies-monitor-package}/bin/pvr-movies-monitor";
                Restart = "always";
                DynamicUser = true;
              };
            };

            system.stateVersion = "26.05";
          };
      };
    }
  ]);
}
