{
	"data": "ENC[AES256_GCM,data:yXL2ZA3jLzIX4oQRi/B0Q2K2LcQsNeUODEm2wszcl1cRGSA/Yw2itEZe4Gun0IknfSOvAgwYasPjzoIudLrceF8OSNag2gYDyCYjCZVxYzqge90miRWDjmUFFcHe9uUTETrZ+5EZdk9Jz6n5+K1o1R+oDBN8MBwAe1B+IohNErPquTuuZ/XSyhxXJEqCA87e7p9kICVBUA/clWN59e92eYYoOVFdsA6NzJu5h8RKxpFsWBRUyQA+UxjGrtNtgR2lc76I2vCwnEBMG0cylb8VxK4FhfZrIw15M3JIauTzLUFHGBALoooIdeiw6cIGqrxtcCOY8MYk5a7DryXH1u+uht1Q+SxPpYFsG2Ii38d54xUIYcegs6cGxABSZIpWBQxroKdXnooMxDS7v5plOMMXvdHLCWPtqttko4dBTXj3rmfxnx7PPYhnHHwd6khGeeyzV9IdX+FUlQe/nLR5q/WadOJ47qHiRg2ZAWacURQf620YCD90vHXffm5l5T5TD4NSaoVy7Bt6ppm8tAM2fCXsp+f5syxAKxoF4xbv3W3DYSeS4YZn0TsTYa1oI4qDs5Lfv8liR6tDxgiiNaQezVzPw/sDOCu7wc7fIeHnJe2p6iv5iJbyM4rLIwzhaExnvgfH4m8vQQ1B8q/e0+PXBdPhNvCSZw9xEc/cSAQd/XvFu4LpuqSfCx1LEPVBp8UKsAyzqglZXVry0u3/3yoHcSeJlsyrkng1E1iqApWLy24Fr87AjCeqhnmztUSOJQ==,iv:WScTK8B5Qat1wHHxmEaKCQT7zcyrRpdO2Ok0dnO7J6U=,tag:QgZxXGdo7i6npLmflcBsRg==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGprYWF3USBIQ29w\nQnV6SFp2UGVCanp2dHBTdmJFT28zWUpXUGRXem1TUlRxN2c1QWlZCkxzL0JRQlRv\nMDZ4K3p5WUhIU1hIeVBUZWYzTnQxQXVQTHByYSs5dzJaK3MKLS0tIDJ5d2UzUDk1\nWjN6dWlCSjRvdFVtT0d0YWpRZlo0RHcwMVQvNzd2c3VkUUkKOab5oJ0EQoqezJeb\na4/6QAKU7Tn0t7IzN2e6h20hiJLr7Gn+l4o9HYKzRtgEBHOL9aVtp2CKMNxs7LiM\nYG7o5w==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAX88KLYCUWS1IKTGsgIRIHwGxTyfhsiRyAgtv65GEEm ishan@turquoise"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaHVBalkvSUNDUzhHM3Yx\nd0l4Z1ptT2RuektNRjl2SDl2THpaUVAzeVdjCjNsYnNmcUFkVTZ1NTA2WDloVVVN\nand5empLajVmVmt6cDJwaFI4NEZlYjgKLS0tIFU3Nk9IRUF6VXlxUVdHWDc5L2RM\nT3IyT21US25NUWFVMVE3eEJGZ2xETHMKQ+o+5KIbkf5KIJyn0DOth0XNdoShTL6R\nggkCgw4Oy/l2MLStidERztCMk2dYuGmGgxDlcW3AmjytTPfJVcmHog==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age13ks0vqf5dnavpq29ukkuhwgk4a2r5cdk52g9ls0aalcd0wg6yy2sq2fpwc"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqaHhMSWVCUDNWTmc5VmF4\nWGFkTEFWZ09EMEtMREYvK3JKNWhzb2hQNnk4Ck1UT2M2K2s3d2pERzhEQTgydzVy\nK0Vqdy82MEdNMmw3ajhQeHdLYnpaSzAKLS0tIFhYR296K0JtNE9Wb3NFZnFybnYy\nL2FHR1VlTUZmZ25xVGlCMm1kaXh0alUKM0OTcfXrJm7lJV4+op3HjPeKHo8eIoQi\nnWOrZ+caMM4pq3L1n5JD1ADys32A9dUYFDIIyjYJBF0BJQFa0Z5AWQ==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yzg8yagn35ltasll84ghskth9jz9ve2lar43hvk438z9velxl5jsunzt08"
			}
		],
		"lastmodified": "2026-09-08T11:12:57Z",
		"mac": "ENC[AES256_GCM,data:bn4yNVOP9CTKf3fMEHv2gsFOiC/L3wd0BlebpecrBRex3V4+AYPJJqM/bS1/atN1Ia2gKrBDFAuDo5YuqsQw2dtDtHlWjGc/g6585hLGo5DiC5J2heC2I9YvLEldyRqyofAMQA4dxb/m6A6rutSFuj8t0du2B1hVk3x42fE7834=,iv:AXBjNRcyLKuRAneAlt180VqbLl4nbz312cW7jDxUb4M=,tag:uzQcJnTO+TaHQN60Dtkdig==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.13.3"
	}
}
